<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="common_properties.urdf.xacro" />
    <xacro:include filename="mobile_base.urdf.xacro" />
    <xacro:include filename="mobile_base_gazebo.urdf.xacro" />
    <xacro:include filename="arm.urdf.xacro" />
    <xacro:include filename="arm_gazebo.urdf.xacro" />
    <xacro:include filename="camera.urdf.xacro" />

    <joint name="mobile_base_arm_joint" type="fixed">
        <parent link="base_link" />
        <child link="arm_base_link" />
        <origin xyz="${base_length / 4.0} 0 ${base_height}" rpy="0 0 0" />
    </joint>

</robot>